# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5cb7c72409d7715464e1107a3985e479772f32fedc4a394152cf0ab9bccbdc553ffff341535224be3d62e270855b49f22997754b76a7039e1dd032e96bd628

test:
  secret_key_base: 10afc44ab0fb2812aecc59fb4ebd4df7133b16cc7d7ddf6a38b4b480044df02981cf1ca473ff00cb5c0545b34ad86726d162d532c72928084197af9735ec3920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
